### ISSUE TITLE
misp.anyEvent prototype not showing in the prototype list

### ISSUE THREAD

**Issue by alexmoldovanbv** [PaloAltoNetworks/minemeld-misp#7]
Hi there,

After installing and activating the extension, I've tried to run the the following commands from my Desktop Ubuntu 16.04 shell:

$ sudo -u minemeld mm-supervisorctl restart minemeld-web

The command supervisorctl is not recognized. 

I've restarted the minemeld engine and searched the misp.anyEvent prototype. I couldn't locate it in my prototype list. 

The extension seems to be active and I didn't receive any errors while installing it.

Do you have any suggestion on how I can proceed?

Thanks!

**Comment by alexmoldovanbv** [comment]
By restarting the API, the issue was solved.

**Comment by jtschichold** [comment]
I have replicated the problem and created https://github.com/PaloAltoNetworks/minemeld-core/issues/294 to track this. Thanks for reporting.
